import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import "../assets/css/home-page.css";
function ReturnPolicy() {
    const currentDate = new Date().toLocaleDateString("en-IN", {
        year: "numeric",
        month: "long",
        day: "numeric",
    });
    return (_jsx(_Fragment, { children: _jsx(_Fragment, { children: _jsx("section", { className: "sub-page-content-container terms-content-container returns-page-content-container", children: _jsxs("div", { className: "container", children: [_jsx("div", { className: "sub-page-hdng-content", children: _jsx("h2", { children: "Return Policy" }) }), _jsxs("div", { className: "sub-page-content", children: [_jsxs("h4", { children: ["Effective Date: ", currentDate] }), _jsx("p", { className: "sub-para", children: "We want you to love every Botaniq Glow product. If something\u2019s not right, here\u2019s how we can help." }), _jsxs("div", { className: "terms-content", children: [_jsx("h5", { children: "1. Returns Eligibility" }), _jsx("p", { className: "fw-semibold ps-4", children: "You may return a product if:" }), _jsxs("ul", { className: "returns-policy-li", children: [_jsx("li", { children: "It is unused and in its original packaging." }), _jsx("li", { children: "The return request is made within 7 days of delivery." }), _jsx("li", { children: "You have the invoice or order confirmation email." })] }), _jsx("p", { className: "ps-4 fw-semibold fst-italic", children: "We do not accept returns for used products due to hygiene reasons." }), _jsx("br", {}), _jsx("h5", { children: "2. How to Initiate a Return" }), _jsxs("p", { className: "fw-semibold ps-4", children: ["Email us at ", _jsx("a", { href: "mailto:support@botaniqglow.com", children: "support@botaniqglow.com" }), " with:"] }), _jsxs("ul", { className: "returns-policy-li", children: [_jsx("li", { children: "Your order number" }), _jsx("li", { children: "Reason for return" }), _jsx("li", { children: "Photos of the product (if applicable)" })] }), _jsx("p", { className: "ps-4 fw-semibold fst-italic", children: "Our team will respond within 1\u20132 business days with next steps." }), _jsx("br", {}), _jsx("h5", { children: "3. Refunds" }), _jsxs("ul", { className: "returns-policy-li", children: [_jsx("li", { children: "Once approved and received, refunds are processed within 5\u20137 business days to the original payment method." }), _jsx("li", { children: "Shipping charges (if any) are non-refundable." })] }), _jsx("br", {}), _jsx("h5", { children: "4. Damaged or Incorrect Items" }), _jsx("p", { className: "ps-4", children: "If your order arrived damaged or incorrect, please contact us within 48 hours of delivery. We\u2019ll arrange a replacement or refund immediately." }), _jsx("br", {}), _jsx("h5", { children: "5. Cancellations" }), _jsx("p", { children: "Orders can be canceled before they are shipped. Once dispatched, they cannot be canceled but may be eligible for return as per above terms." })] })] }), _jsx("h4", { children: "Need Help?" }), _jsxs("p", { style: { fontSize: "18px" }, children: ["Reach us at ", _jsx("a", { href: "mailto:support@botaniqglow.com", className: "terms-mail", children: "support@botaniqglow.com" })] })] }) }) }) }));
}
export default ReturnPolicy;
